language: java
jdk:
- oraclejdk8
env:
  global:
  - TERM=dumb
branches:
  only:
  - master
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
deploy:
  provider: heroku
  api_key:
    secure: dFqz/bdLopspavhyaN9SqeOPEjfjIG7zdUUlH+lulZY8bWgW9lkaIGU6aK5PpRsiiUqiw+uXtdCsWxA/sGmrZwUN4qlKAM0vHjfvE1DhROVUHiW8OZpwuBds7uIgH4IOUO9pTAZmE9lbgeMDGRr1/XF0QsvQFuQHw1ONUeBdO92m2XSnxX/yuIRDhIAcTrTdiRgI5XLK2nASbAhVg5734kqLX7f4xDAhmwFn6A5rY86nV4XpW3BY/G/usLlWMNzcE1UQjQgQIFMMQr2EDjz6vsMub5sEAsbtPUVVdpMoL4Fhdt5naxrAz9T+psK4E8myD9VNSi7O5OVsuAAm3hjFuB+FzGlqOuK3PuWhlOCdj8qXLpL2S+Y5uRXF7SjLk49rO/6pURL0sUPqTcVVFB8pKtpBduqRrXGRKQIatilAaqvdmgwVCTeGIkHHvoYXP6W79JNCd5dFYUdZOxpA+ffE2NSgukV+kIiN1FT6YPmxpCjdaKMsoI2xgMPZOr4ro3/x1f+DUexgv08TYhM6fgyzEgY+lEedJwJFP0+sBFj5xZ+Q4Bm7cisawrJlVQLE60XKzSmuOEppcFqFED+paZYMxPgJ9cHv9fcGJkfsDJTL1W/9UDRcjI7jAXkf57xguABSf6cjsyCEkb6eRDfv1bLBUsnuaHYXVQ6f7N7zNgAD3PE=
  app: ancient-bastion-71600
  on:
    repo: makeheureux/java-molecule-example
